/* GEOTRACE — constellation.js (original, unchanged) */
(function(){
'use strict';
const hero=document.querySelector('.hero');if(!hero)return;
const canvas=document.createElement('canvas');canvas.id='constellation-canvas';canvas.setAttribute('aria-hidden','true');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:2;';hero.style.position='relative';hero.appendChild(canvas);
const interactLayer=document.createElement('div');interactLayer.style.cssText='position:absolute;inset:0;z-index:3;cursor:crosshair;';hero.appendChild(interactLayer);
const ctx=canvas.getContext('2d');let W,H;const points=[],particles=[],MAX_POINTS=8;
function resize(){const rect=hero.getBoundingClientRect();W=canvas.width=rect.width;H=canvas.height=rect.height;}resize();window.addEventListener('resize',resize);
interactLayer.addEventListener('click',(e)=>{const rect=hero.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;if(points.length>=MAX_POINTS){const removed=points.shift();spawnBreakParticles(removed.x,removed.y);}points.push({x,y,r:0,alpha:0,phase:Math.random()*Math.PI*2,hue:Math.random()>0.5?192:268,rings:[{r:0,alpha:0.8}]});});
function spawnBreakParticles(x,y){for(let i=0;i<12;i++){const angle=(Math.PI*2*i)/12+Math.random()*0.5,speed=1+Math.random()*2.5;particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,alpha:0.9,r:2+Math.random()*3,hue:192,life:1});}}
const lineProgress=new Map();function lineKey(i,j){return`${Math.min(i,j)}-${Math.max(i,j)}`;}
let t=0;
function draw(){requestAnimationFrame(draw);ctx.clearRect(0,0,W,H);t+=0.016;
for(let i=0;i<points.length;i++){for(let j=i+1;j<points.length;j++){const a=points[i],b=points[j],dx=b.x-a.x,dy=b.y-a.y,dist=Math.sqrt(dx*dx+dy*dy);if(dist>320)continue;const key=lineKey(i,j);let prog=lineProgress.get(key)||0;prog=Math.min(prog+0.03,1);lineProgress.set(key,prog);const endX=a.x+dx*prog,endY=a.y+dy*prog,opacity=(1-dist/320)*0.5*Math.min(a.alpha,b.alpha);ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(endX,endY);ctx.strokeStyle=`hsla(${(a.hue+b.hue)/2},85%,65%,${opacity*0.3})`;ctx.lineWidth=3;ctx.filter='blur(3px)';ctx.stroke();ctx.restore();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(endX,endY);const grad=ctx.createLinearGradient(a.x,a.y,endX,endY);grad.addColorStop(0,`hsla(${a.hue},85%,65%,${opacity})`);grad.addColorStop(1,`hsla(${b.hue},85%,65%,${opacity})`);ctx.strokeStyle=grad;ctx.lineWidth=0.8;ctx.stroke();const dotPos=(Math.sin(t*1.5+i+j)*0.5+0.5)*prog,dotX=a.x+dx*dotPos,dotY=a.y+dy*dotPos;ctx.beginPath();ctx.arc(dotX,dotY,1.5,0,Math.PI*2);ctx.fillStyle=`hsla(192,100%,75%,${opacity*1.5})`;ctx.fill();}}
points.forEach((p,idx)=>{p.r=Math.min(p.r+0.3,6);p.alpha=Math.min(p.alpha+0.05,1);const pulse=0.7+0.3*Math.sin(t*2+p.phase);const halo=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,30);halo.addColorStop(0,`hsla(${p.hue},90%,65%,${0.25*p.alpha*pulse})`);halo.addColorStop(1,`hsla(${p.hue},90%,65%,0)`);ctx.beginPath();ctx.arc(p.x,p.y,30,0,Math.PI*2);ctx.fillStyle=halo;ctx.fill();p.rings.forEach((ring,ri)=>{ring.r+=0.8;ring.alpha-=0.012;if(ring.alpha<=0){p.rings.splice(ri,1);return;}ctx.beginPath();ctx.arc(p.x,p.y,ring.r,0,Math.PI*2);ctx.strokeStyle=`hsla(${p.hue},85%,65%,${ring.alpha*p.alpha})`;ctx.lineWidth=1;ctx.stroke();});if(Math.random()<0.02)p.rings.push({r:p.r,alpha:0.6});const coreGrad=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,p.r*pulse);coreGrad.addColorStop(0,`hsla(${p.hue},100%,95%,${p.alpha})`);coreGrad.addColorStop(0.4,`hsla(${p.hue},90%,70%,${p.alpha*0.9})`);coreGrad.addColorStop(1,`hsla(${p.hue},85%,60%,0)`);ctx.beginPath();ctx.arc(p.x,p.y,p.r*pulse,0,Math.PI*2);ctx.fillStyle=coreGrad;ctx.fill();ctx.save();ctx.translate(p.x,p.y);ctx.rotate(t*0.3+p.phase);ctx.strokeStyle=`hsla(${p.hue},100%,85%,${p.alpha*0.6})`;ctx.lineWidth=0.8;const sparkLen=p.r*2.5*pulse;[-1,1].forEach(d=>{ctx.beginPath();ctx.moveTo(-sparkLen*d,0);ctx.lineTo(sparkLen*d,0);ctx.stroke();ctx.beginPath();ctx.moveTo(0,-sparkLen*d);ctx.lineTo(0,sparkLen*d);ctx.stroke();});ctx.restore();ctx.font='9px JetBrains Mono,monospace';ctx.fillStyle=`hsla(${p.hue},80%,70%,${p.alpha*0.8})`;ctx.fillText(`PT${idx+1}`,p.x+10,p.y-10);});
particles.forEach((par,i)=>{par.x+=par.vx;par.y+=par.vy;par.vy+=0.05;par.alpha-=0.025;par.r*=0.97;if(par.alpha<=0){particles.splice(i,1);return;}ctx.beginPath();ctx.arc(par.x,par.y,par.r,0,Math.PI*2);ctx.fillStyle=`hsla(${par.hue},90%,70%,${par.alpha})`;ctx.fill();});
lineProgress.forEach((_,key)=>{const[ai,bi]=key.split('-').map(Number);if(ai>=points.length||bi>=points.length)lineProgress.delete(key);});}
draw();
const hint=document.createElement('div');hint.setAttribute('aria-hidden','true');hint.style.cssText='position:absolute;bottom:24px;left:50%;transform:translateX(-50%);font-family:"JetBrains Mono",monospace;font-size:10px;letter-spacing:2px;color:rgba(6,182,212,0.5);pointer-events:none;z-index:4;animation:fade-up 0.6s ease 2s both;text-transform:uppercase;';hint.textContent='✦ Click anywhere to place location markers ✦';hero.appendChild(hint);
interactLayer.addEventListener('click',()=>{hint.style.opacity='0';hint.style.transition='opacity 0.5s';},{once:true});
})();
