/* GEOTRACE — enhancements.js (original, unchanged) */
(function(){
'use strict';
function setupHoverGlows(){const hoverTargets=document.querySelectorAll('.btn-primary,.btn-ghost,.nav-cta,.feature-card,.stat-card,.testimonial-card,.glass,.panel-card,.upload-zone');hoverTargets.forEach(el=>{el.addEventListener('mousemove',e=>{const rect=el.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,xPct=(x/rect.width)*100,yPct=(y/rect.height)*100;el.style.setProperty('--mouse-x',`${xPct}%`);el.style.setProperty('--mouse-y',`${yPct}%`);el.classList.add('mouse-glow');});el.addEventListener('mouseleave',()=>{el.classList.remove('mouse-glow');el.style.removeProperty('--mouse-x');el.style.removeProperty('--mouse-y');});});}
function setupScrollFade(){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('enhance-visible');observer.unobserve(entry.target);});},{threshold:0.08,rootMargin:'0px 0px -40px 0px'});const grids=document.querySelectorAll('.features-grid,.stats-row,.testimonials-grid,.how-steps,.admin-stats-row');grids.forEach(grid=>{Array.from(grid.children).forEach((child,i)=>{child.classList.add('enhance-child');child.style.transitionDelay=`${i*80}ms`;observer.observe(child);});});document.querySelectorAll('.trust-logo,.footer-link,.step-num').forEach((el,i)=>{el.classList.add('enhance-child');el.style.transitionDelay=`${i*30}ms`;observer.observe(el);});}
function setupRipple(){document.querySelectorAll('.btn-primary,.btn-ghost,.nav-cta,.map-btn').forEach(btn=>{btn.addEventListener('click',e=>{const rect=btn.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;const ripple=document.createElement('span');ripple.className='btn-ripple';ripple.style.cssText=`position:absolute;left:${x}px;top:${y}px;width:0;height:0;background:rgba(255,255,255,0.25);border-radius:50%;transform:translate(-50%,-50%);animation:ripple-expand 0.6s ease-out forwards;pointer-events:none;z-index:10;`;const wasRelative=getComputedStyle(btn).position;if(wasRelative==='static')btn.style.position='relative';btn.style.overflow='hidden';btn.appendChild(ripple);setTimeout(()=>ripple.remove(),700);});});}
function setupCardTilt(){const cards=document.querySelectorAll('.feature-card,.stat-card,.glass');cards.forEach(card=>{card.addEventListener('mousemove',e=>{const rect=card.getBoundingClientRect(),x=e.clientX-rect.left-rect.width/2,y=e.clientY-rect.top-rect.height/2,rotX=(-y/rect.height)*8,rotY=(x/rect.width)*8;card.style.transform=`perspective(600px) rotateX(${rotX}deg) rotateY(${rotY}deg) scale(1.02)`;card.style.transition='transform 0.1s linear';});card.addEventListener('mouseleave',()=>{card.style.transform='';card.style.transition='transform 0.4s ease';});});}
function setupScrollProgress(){if(!document.querySelector('.hero-headline'))return;const bar=document.createElement('div');bar.setAttribute('aria-hidden','true');bar.style.cssText='position:fixed;top:0;left:0;height:2px;width:0%;background:linear-gradient(90deg,#7c3aed,#06b6d4,#e879f9);z-index:9999;transition:width 0.1s linear;box-shadow:0 0 8px rgba(6,182,212,0.6);';document.body.appendChild(bar);window.addEventListener('scroll',()=>{const total=document.documentElement.scrollHeight-window.innerHeight,pct=(window.scrollY/total)*100;bar.style.width=`${pct}%`;},{passive:true});}
function init(){setupHoverGlows();setupScrollFade();setupRipple();setupCardTilt();setupScrollProgress();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
