/* GEOTRACE — main.js (original) */
(function(){
'use strict';
const dot=document.getElementById('cursor-dot'),ring=document.getElementById('cursor-ring');
if(dot&&ring){let rx=0,ry=0,mx=0,my=0;document.addEventListener('mousemove',(e)=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px';});(function loop(){rx+=(mx-rx)*0.14;ry+=(my-ry)*0.14;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(loop);})();document.querySelectorAll('a,button,.feature-card,.testimonial-card,.marquee-item,.upload-zone').forEach(el=>{el.addEventListener('mouseenter',()=>ring.classList.add('hovered'));el.addEventListener('mouseleave',()=>ring.classList.remove('hovered'));});document.addEventListener('mouseleave',()=>{dot.style.opacity='0';ring.style.opacity='0';});document.addEventListener('mouseenter',()=>{dot.style.opacity='1';ring.style.opacity='1';});}
const nav=document.querySelector('.nav');
if(nav){window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>20),{passive:true});}
const toggle=document.querySelector('.nav-toggle'),links=document.querySelector('.nav-links'),cta=document.querySelector('.nav-cta');
if(toggle&&links){toggle.addEventListener('click',()=>{const open=links.classList.toggle('open');toggle.setAttribute('aria-expanded',open);if(cta)cta.classList.toggle('open',open);const spans=toggle.querySelectorAll('span');if(open){spans[0].style.transform='translateY(7px) rotate(45deg)';spans[1].style.opacity='0';spans[2].style.transform='translateY(-7px) rotate(-45deg)';}else{spans.forEach(s=>{s.style.transform='';s.style.opacity='';})}});links.querySelectorAll('a').forEach(a=>{a.addEventListener('click',()=>{links.classList.remove('open');if(cta)cta.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.querySelectorAll('span').forEach(s=>{s.style.transform='';s.style.opacity='';});});});}
const reveals=document.querySelectorAll('.reveal');
if('IntersectionObserver' in window&&reveals.length){const io=new IntersectionObserver((entries)=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target);}});},{threshold:0.1,rootMargin:'0px 0px -60px 0px'});reveals.forEach(el=>io.observe(el));}else{reveals.forEach(el=>el.classList.add('visible'));}
function animateCounters(){document.querySelectorAll('[data-count]').forEach(el=>{const target=parseFloat(el.dataset.count),suffix=el.dataset.suffix||'',start=performance.now();(function step(now){const prog=Math.min((now-start)/2000,1),ease=1-Math.pow(1-prog,4),cur=target*ease;if(target>=1000000)el.textContent=(cur/1000000).toFixed(1)+'M'+suffix;else if(target>=1000)el.textContent=Math.round(cur).toLocaleString()+suffix;else if(target%1!==0)el.textContent=cur.toFixed(1)+suffix;else el.textContent=Math.round(cur)+suffix;if(prog<1)requestAnimationFrame(step);})(start);});}
const heroStats=document.querySelector('.hero-stats');
if(heroStats&&'IntersectionObserver' in window){let fired=false;const io=new IntersectionObserver((entries)=>{if(entries[0].isIntersecting&&!fired){fired=true;animateCounters();io.disconnect();}},{threshold:0.3});io.observe(heroStats);}else{animateCounters();}
const tw=document.getElementById('typewriter');
if(tw){const words=['PHOTO','IMAGE','LOCATION','MOMENT','MEMORY'];let wi=0,ci=0,deleting=false;function type(){const word=words[wi];if(deleting){ci--;tw.textContent=word.substring(0,ci);if(ci===0){deleting=false;wi=(wi+1)%words.length;setTimeout(type,400);return;}setTimeout(type,60);}else{ci++;tw.textContent=word.substring(0,ci);if(ci===word.length){deleting=true;setTimeout(type,2000);return;}setTimeout(type,110);}}setTimeout(type,1500);}
const track=document.querySelector('.marquee-track');
if(track)track.innerHTML+=track.innerHTML;
document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener('click',(e)=>{const target=document.getElementById(a.getAttribute('href').slice(1));if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'});}});});
const bar=document.createElement('div');bar.id='scroll-progress';document.body.appendChild(bar);
window.addEventListener('scroll',()=>{const total=document.documentElement.scrollHeight-window.innerHeight;bar.style.width=(window.scrollY/total*100)+'%';},{passive:true});
window.GeoTrace=window.GeoTrace||{};
window.GeoTrace.toast=function(msg,type='info',duration=4000){let container=document.getElementById('toast-container');if(!container){container=document.createElement('div');container.id='toast-container';container.style.cssText='position:fixed;bottom:24px;right:24px;z-index:9999;display:flex;flex-direction:column;gap:12px;';document.body.appendChild(container);}const colors={info:'var(--neon-cyan)',success:'var(--neon-green)',error:'var(--neon-red)',warn:'var(--neon-gold)'},icons={info:'ℹ️',success:'✅',error:'❌',warn:'⚠️'},toast=document.createElement('div');toast.style.cssText=`padding:12px 20px;border-radius:10px;background:rgba(8,13,24,0.95);border:1px solid ${colors[type]||colors.info};color:var(--text-primary);font-size:14px;font-family:var(--font-body);box-shadow:0 4px 24px rgba(0,0,0,0.4);animation:toast-in 0.3s ease;max-width:340px;display:flex;align-items:center;gap:10px;`;toast.innerHTML=`<span>${icons[type]||''}</span><span>${msg}</span>`;container.appendChild(toast);setTimeout(()=>{toast.style.animation='toast-out 0.3s ease forwards';setTimeout(()=>toast.remove(),300);},duration);};
})();
